apiVersion: v1
kind: Pod
metadata:
  name: curl-sa
spec:
  serviceAccountName: foo
  containers:
    - name: main
      image: tutum/curl
      command: ["tail", "-f", "/dev/null"]
    - name: ambassador
      image: luksa/kubectl-proxy:1.6.2
