apiVersion: apps/v1
kind: Deployment
metadata:
    name: web
spec:
    minReadySeconds: 10
    replicas: 3
    progressDeadlineSeconds: 30
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        type: RollingUpdate
    selector:
        matchLabels:
            app: web
    template:
        metadata:
            name: web
            labels:
                app: web
        spec:
            containers:
                - image: luksa/kubia:v3
                  name: web
                  readinessProbe:
                      periodSeconds: 1
                      httpGet:
                          port: 8080
                          path: /
