apiVersion: v1
kind: Pod
metadata:
  name: priviledged-pod
spec:
  hostIPC: true
  hostPID: true
  containers:
    - name: ubuntu
      image: ubuntu
      imagePullPolicy: IfNotPresent
      command: ["tail", "-f", "/dev/null"]
      securityContext:
        privileged: true
