apiVersion: v1
kind: Pod
metadata:
    name: fortune
spec:
    volumes:
        - name: html
          emptyDir: {}
        - name: config
          configMap:
              name: fortune-config
              items:
                  - key: nginx.conf
                    path: https.conf
        - name: certs
          secret:
              secretName: fortune-https

    containers:
        - name: fortune-generator
          image: matusdubrava/fortune:env
          volumeMounts:
              - name: html
                mountPath: /var/htdocs
          env:
              - name: INTERVAL
                valueFrom:
                    configMapKeyRef:
                        name: fortune-config
                        key: sleep-interval
        - name: webserver
          image: nginx
          ports:
              - name: http
                containerPort: 80
                protocol: TCP
              - name: https
                containerPort: 443
                protocol: TCP
          volumeMounts:
              - name: html
                mountPath: /usr/share/nginx/html
                readOnly: true
              - name: config
                mountPath: /etc/nginx/conf.d
                readOnly: true
              - name: certs
                mountPath: /etc/nginx/certs/
                readOnly: true
