apiVersion: v1
kind: Pod
metadata:
  name: app-pod-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - name: app
      image: app
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          protocol: TCP
