apiVersion: v1
kind: Pod
metadata:
    name: fortune
    labels:
        app: fortune
spec:
    volumes:
        - name: html
          emptyDir: {}
        - name: config
          configMap:
              name: fortune-config
    containers:
        - name: fortune-generator
          image: matusdubrava/fortune:env
          volumeMounts:
              - name: html
                mountPath: /var/htdocs
          env:
              - name: INTERVAL
                valueFrom:
                    configMapKeyRef:
                        name: fortune-config
                        key: sleep-interval
        - name: webserver
          image: nginx
          ports:
              - name: http
                containerPort: 80
                protocol: TCP
          volumeMounts:
              - name: html
                mountPath: /usr/share/nginx/html
              - name: config
                mountPath: /etc/nginx/conf.d
