apiVersion: v1
kind: Pod
metadata:
    name: fortune
spec:
    volumes:
        - name: html
          emptyDir: {}
        - name: config
          configMap:
              name: fortune-config
              items:
                  - key: nginx.conf
                    path: gzip.conf
    containers:
        - name: fortune-generator
          image: matusdubrava/fortune:env
          volumeMounts:
              - name: html
                mountPath: /var/htdocs
          env:
              - name: INTERVAL
                valueFrom:
                    configMapKeyRef:
                        name: fortune-config
                        key: sleep-interval
        - name: webserver
          image: nginx
          volumeMounts:
              - name: html
                mountPath: /usr/share/nginx/html
              - name: config
                mountPath: /etc/nginx/conf.d
          ports:
              - name: http
                containerPort: 80
                protocol: TCP
