apiVersion: v1
kind: Pod
metadata:
    name: fortune
spec:
    containers:
        - name: html-generator
          image: matusdubrava/fortune-args
          args: ['2']
          volumeMounts:
              - name: html
                mountPath: /var/htdocs
        - name: nginx
          image: nginx
          volumeMounts:
              - name: html
                mountPath: /usr/share/nginx/html
    volumes:
        - name: html
          emptyDir:
              medium: Memory
