version: '2'

services:
    drupal:
        image: drupal
        ports:
            - '8080:80'
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
        depends_on:
            - postgreDB

    postgreDB:
        image: postgres
        environment:
            - POSTGRES_DB=drupal
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
        volumes:
            - 'dbdata:/var/lib/postgresql/data'

volumes:
    dbdata:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
